# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform : 'Any CPU'
  BuildVersion: 1.4.$(Build.BuildId) #Version 1.3+ contains C# 8 nullable types

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.3.0'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/**/*.sln'
    feedsToUse: 'select'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/**/*.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'https://pkgs.dev.azure.com/microcapitaluk/_packaging/microcapitaluk/nuget/v3/index.json'
    allowPackageConflicts: true

