# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# YAML schema reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

trigger:
- master

stages:

- stage: 'Build'
  variables:
    buildConfiguration: 'Release'

  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
 
    variables: 
      BuildConfiguration: 'release'

    workspace:
      clean: all

    steps:

    - task: NuGetCommand@2
      inputs:
       command: custom
       arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
    - script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch

    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 2.2.104' 
      inputs: 
        version: 2.2.104
 
    - task: DotNetCoreCLI@2
      displayName: "NuGet Restore"
      inputs:
        command: restore
        projects: '**/*.csproj'


    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: './**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        nobuild: true 
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.NuGetVersion
 
    - task: DotNetCoreCLI@2 
      displayName: 'dotnet nuget push' 
      inputs: 
        command: push 
        publishVstsFeed: '30b3c958-b5a1-4cd0-af1e-a9179ee58323' 
        versioningScheme: byBuildNumber
