# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# YAML schema reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

trigger:
- master

stages:

- stage: 'Build'
  variables:
    buildConfiguration: 'Release'

  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
 
    variables: 
      BuildConfiguration: 'release'

    workspace:
      clean: all

    steps:


    - task: GitVersion@5
      inputs:
        runtime: 'core'

    - task: NuGetCommand@2
      displayName: 'nuget restore'
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        vstsFeed: '30b3c958-b5a1-4cd0-af1e-a9179ee58323'

    - task: DotNetCoreCLI@2
      displayName: "Build Solution"
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
        versioningScheme: byBuildNumber
        
        
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack' 
      inputs: 
        command: pack
        packagesToPack: '**/*.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)\Nuget'
        nobuild: true 
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion    
